# Generated by Django 5.2.8 on 2025-11-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('update_type', models.CharField(choices=[('pricing', 'Pricing Change'), ('campaign', 'Marketing Campaign'), ('release', 'Product Release'), ('partnership', 'Partnership'), ('news', 'News/Announcement'), ('feature', 'Feature Update'), ('other', 'Other')], default='other', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('impact_score', models.IntegerField(default=0, help_text='0-100 scale for impact assessment')),
                ('is_high_impact', models.BooleanField(default=False)),
                ('source', models.CharField(default='website', help_text='Source: website, social, etc.', max_length=100)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='monitor.competitor')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_interval_hours', models.IntegerField(default=24, help_text='Hours between checks')),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to monitor')),
                ('competitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_config', to='monitor.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.competitorupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trend_type', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(help_text='Number of occurrences')),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0-1 scale')),
                ('related_updates', models.ManyToManyField(related_name='trends', to='monitor.competitorupdate')),
            ],
            options={
                'ordering': ['-last_detected'],
            },
        ),
        migrations.AddIndex(
            model_name='competitorupdate',
            index=models.Index(fields=['-detected_at'], name='monitor_com_detecte_af1c07_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorupdate',
            index=models.Index(fields=['update_type'], name='monitor_com_update__f1ccc2_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorupdate',
            index=models.Index(fields=['is_high_impact'], name='monitor_com_is_high_59218a_idx'),
        ),
    ]
